export const EcoSystems = [
  {
    id: 1,
    name: 'JoyID',
    logo: '/ecosystems/joyid.svg',
    desc: 'JoyID is a multichain, cross-platform, passwordless and mnemonic-free wallet solution based on FIDO Webauthn protocol and Nervos CKB.',
    field: ['Wallet'],
    twitter: 'https://twitter.com/joy_protocol',
    website: 'https://joy.id/',
  },
  {
    id: 2,
    name: 'Soulland',
    logo: '/ecosystems/soulland.png',
    desc: 'Global First Social Feeds-Themed Metaverse.',
    field: ['Social-Fi', 'Metaverse'],
    twitter: 'https://twitter.com/soulland_en',
    website: 'https://www.soulland.xyz/',
  },
  {
    id: 3,
    name: 'Kolo Market',
    logo: '/ecosystems/kolo_market.png',
    desc: 'The world\'s first web3 classical Music platform.',
    field: ['NFT'],
    twitter: 'https://twitter.com/joy_protocol',
    website: 'https://twitter.com/KOLONFT',
  },
  {
    id: 4,
    name: 'ACG Worlds',
    logo: '/ecosystems/joyid.svg',
    desc: '⛩  Build the world\'s largest Web3.0 #Metaverse theme park.',
    field: ['Metaverse'],
    twitter: 'https://twitter.com/ACGWORLDS_META',
    website: 'https://acgworlds.com/',
  },
  {
    id: 5,
    name: 'XY Finance',
    logo: '/ecosystems/XY_Finance.png',
    desc: 'Cross-chain swap assets to zkSync, Optimism, Arbitrum, Linea, Base, Scroll and 14 other major EVMs',
    field: ['DEX'],
    twitter: 'https://twitter.com/xyfinance',
    website: 'https://app.xy.finance/',
  },
  {
    id: 6,
    name: 'IC1101',
    logo: '/ecosystems/ic1101.png',
    desc: 'Index Catalogue 1101 (Designation A2029-BCG) is a class S0 supergiant lenticular galaxy at the center of the Abell 2029 galaxy cluster.',
    field: ['Metaverse'],
    twitter: 'https://twitter.com/IC1101World',
    website: 'https://ic1101.world/',
  },
  {
    id: 7,
    name: 'Cyber8Ball',
    logo: '/ecosystems/cyber8ball.png',
    desc: 'Cyberpunk-themed Play-to-win PVP pool game integrating NFTs, token exchange and more. 🎱 ',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/Cyber8Ba11',
    website: 'https://www.cyber8ball.xyz/',
  },
  {
    id: 8,
    name: 'Cricket Fly',
    logo: '/ecosystems/Cricket_fly.jpg',
    desc: 'World\'s first Play2Win Web3 Cricket Game! Developed in close collaboration with Gamiflyco and UltiverseDAO.',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/CricketFlyGame',
    website: 'https://gamifly.co/',
  },
  {
    id: 9,
    name: 'MetaMerge',
    logo: '/ecosystems/MetaMerge.webp',
    desc: 'MERGE. EVOLVE. COMBAT. A universe combining AIGC, NFTs and Gaming.',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/MetaMerge_xyz',
    website: 'https://www.metamerge.xyz/',
  },
  {
    id: 10,
    name: 'OWL Networks',
    logo: '/ecosystems/owl_network.jpg',
    desc: 'A decentralized SocialFi platform built by the OW Foundation. ',
    field: ['Social-Fi'],
    twitter: 'https://twitter.com/owlweb3',
  },
  {
    id: 11,
    name: 'opSwap',
    logo: '/ecosystems/opswap.svg',
    desc: 'An AI-enhanced, cross-chain DEX aggregator optimized for the opBNB ecosystem.',
    field: ['DEX'],
    twitter: 'https://twitter.com/opSwap_protocol',
    website: 'https://opswap.io/',
  },
  {
    id: 12,
    name: 'DeGame',
    logo: '/ecosystems/degame.png',
    desc: 'DeGame is the world\'s largest NFT games aggregator, listing over 4000 blockchain game projects and 1000+ tokens & chains since 2021.',
    field: ['Game-Fi','Campaign'],
    twitter: 'https://twitter.com/degame_l2y',
    website: 'https://degame.com/en/home',
  },
  {
    id: 13,
    name: 'Trantor',
    logo: '/ecosystems/trantor.png',
    desc: 'A Unified Web3 Portal Promoting Interconnectivity among communities and brands through Empowered Decentralized Identities ',
    field: ['Campaign', 'DID'],
    twitter: 'https://twitter.com/TrantorDAO',
    website: 'https://trantor.xyz/',
  },
  {
    id: 14,
    name: 'Puffverse',
    logo: '/ecosystems/puffverse.png',
    desc: 'A dreamland Metaverse with a comprehensive ecosystem.',
    field: ['Metaverse'],
    twitter: 'https://twitter.com/Puffverse',
    website: 'https://puffverse.pro/',
  },
  {
    id: 15,
    name: 'INTO',
    logo: '/ecosystems/into.svg',
    desc: 'INTO, a Web3 social protocol based on blockchain and artificial intelligence, integrates functions such as encrypted wallet, SocialFi, SoulBound Token (SBT) and AI-assisted Web3 community operation and management tools.',
    field: ['Social-Fi'],
    twitter: 'https://twitter.com/INTOverse_',
    website: 'https://intoverse.co/',
  },
  {
    id: 16,
    name: 'Chatpuppy',
    logo: '/ecosystems/chatpuppy.png',
    desc: 'A super secured NFT-based wallet-to-wallet instant messanger dApp for WEB3',
    field: ['NFT','Social-Fi'],
    twitter: 'https://twitter.com/chatpuppynft',
    website: 'https://www.chatpuppy.com/',
  },
  {
    id: 17,
    name: 'UneMeta',
    logo: '/ecosystems/unemetawebp.webp',
    desc: 'The NFT market & social space for icons & The NFT Buddy For You.',
    field: ['NFT','Marketplace'],
    twitter: 'https://twitter.com/UNE_METAVERSE',
    website: 'https://www.unemeta.com/',
  },
  {
    id: 18,
    name: 'Legend of Arcadia',
    logo: '/ecosystems/loa.png',
    desc: 'Legend of Arcadia is a multi-chain, free-to-play, and play-to-earn casual strategy card game that combines traditional gaming experience with Web3 GameFi 2.0.',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/LegendofArcadia',
    website: 'https://legendofarcadia.io/',
  },
  {
    id: 19,
    name: 'Port3',
    logo: '/ecosystems/port3.svg',
    desc: 'A social data layer between Web2 and Web3. ',
    field: ['Campaign','Social-Fi'],
    twitter: 'https://twitter.com/Port3Network',
    website: 'https://port3.io/',
  },
  {
    id: 20,
    name: 'RE:DREAMER',
    logo: '/ecosystems/redreamer.webp',
    desc: 'Builder of ERC-6672: Multi-redeemable NFTs | Data Exchange Layer for Real-World Assets ',
    field: ['NFT'],
    twitter: 'https://twitter.com/REDREAMER_Lab',
    website: 'https://www.redreamer.io/',
  },
  {
    id: 21,
    name: 'Cassava Network',
    logo: '/ecosystems/cassavanetwork.webp',
    desc: 'Building African Gateway to web3.',
    field: ['Campaign'],
    twitter: 'https://twitter.com/CassavaNetwork',
    website: 'https://www.cassava.network/',
  },
  {
    id: 22,
    name: 'Popula',
    logo: '/ecosystems/popula.png',
    desc: 'On-chain tools empowering community ownership. (🐝, 🐝)',
    field: ['Social-Fi'],
    twitter: 'https://twitter.com/beepopula',
    website: 'https://popula.io/',
  },
  {
    id: 23,
    name: 'Cat Paradise',
    logo: '/ecosystems/catparadise.png',
    desc: 'Cat Paradise, the purrfect GameFi platform for cat lovers! 🐾',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/catparadise_io',
    website: 'https://www.catparadise.io/',
  },
  {
    id: 24,
    name: 'Tap Fantasy',
    logo: '/ecosystems/tapfantasy.jpg',
    desc: 'Tap Fantasy is an MMORPG blockchain game! Come Tap for Golds! ',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/tapfantasy2021',
    website: 'https://tapfantasy.io/#/',
  },
  {
    id: 25,
    name: 'MetaCene',
    logo: '/ecosystems/metacene.png',
    desc: '🎮Next-gen blockchain MMORPG homeland ',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/MetaCeneGame',
    website: 'https://metacene.io/',
  },
  {
    id: 26,
    name: 'For Metas',
    logo: '/ecosystems/4metas.jpg',
    desc: 'For Metas is building Web3 Application platform which servicing multiple industries and ecosystem',
    field: ['Game-Fi', 'DAO'],
    twitter: 'https://twitter.com/4metas',
    website: 'https://www.4metas.io/#/',
  },
  {
    id: 27,
    name: 'VIP3',
    logo: '/ecosystems/vip3.svg',
    desc: 'VIP3 is the FIRST all-in-one web3 membership platform, providing users with bonus and discounts over 30 web3 apps',
    field: ['Others','Infrastructure'],
    twitter: 'https://twitter.com/web3vip',
    website: 'https://dapp.vip3.io/',
  },
  {
    id: 28,
    name: 'Reyield Finance',
    logo: '/ecosystems/reyield.png',
    desc: 'AI investment platform that simplifies CeFi & DeFi tools.',
    field: ['DeFi'],
    twitter: 'https://twitter.com/REYIELDLabs',
    website: 'https://www.reyield.fi/',
  },
  {
    id: 30,
    name: 'Atem',
    logo: '/ecosystems/atem.webp',
    desc: 'Atem Network is a decentralized content creation protocol, we aim at helping creators tokenize their content and build web3 native communities.',
    field: ['Social-Fi'],
    twitter: 'https://twitter.com/atem_network',
    website: 'https://www.atem.io/',
  },
  {
    id: 31,
    name: 'NFP',
    logo: '/ecosystems/nfp.png',
    desc: 'NFPrompt is the first Prompt Artist Platform in Web3, which lets you mint your imagination into an AI-Generated NFT.',
    field: ['AI','NFT'],
    twitter: 'https://twitter.com/nfprompt',
    website: 'https://nfprompt.io/',
  },
  {
    id: 32,
    name: 'xhashtag',
    logo: '/ecosystems/xHashtag.svg',
    desc: 'Collect reputation and skill #Soultag badges 🥇 and unlock earning opportunities across Web3  🤑',
    field: ['Social-Fi','DID'],
    twitter: 'https://twitter.com/xhashtagio',
    website: 'https://app.xhashtag.io/',
  },
  {
    id: 33,
    name: 'Club3',
    logo: '/ecosystems/club3.png',
    desc: 'The Web3 Community Building Platform',
    field: ['Campaign'],
    twitter: 'https://twitter.com/club3xyz',
    website: 'https://www.club3.xyz/',
  },
  {
    id: 34,
    name: 'TaskOn',
    logo: '/ecosystems/taskon.svg',
    desc: 'TaskOn is a platform that boosts the completion for various Web3 tasks in a decentralized way.',
    field: ['Campaign'],
    twitter: 'https://twitter.com/taskonxyz',
    website: 'https://taskon.xyz/',
  },
  {
    id: 35,
    name: 'Gode Chain',
    logo: '/ecosystems/gode.svg',
    desc: 'Gode Chain is a new generation blockchain',
    field: ['Layer 1'],
    twitter: 'https://twitter.com/GodeChain',
    website: 'https://godechain.com/',
  },
  {
    id: 36,
    name: 'WAM',
    logo: '/ecosystems/wam.png',
    desc: 'Creators of the award-winning #web3 gaming ecosystem $WAM.',
    field: ['Game-Fi','NFT'],
    twitter: 'https://twitter.com/playWAM',
    website: 'https://wam.app/',
  },
  
  {
    id: 37,
    name: 'Magic Square',
    logo: '/ecosystems/magicsquare.svg',
    desc: 'Magic Square: Your Web3 Discovery & Engagement Hub. Explore community-vetted apps and games on the Magic Store Web3 App Store and Earn Rewards ',
    field: ['Campaign','Others'],
    twitter: 'https://twitter.com/MagicSquareio',
    website: 'https://magic.store/',
  },
  
  {
    id: 38,
    name: 'Legend of Cards',
    logo: '/ecosystems/loc.jpg',
    desc: 'An exclusive social poker club comprized of Cardslinger NFTs that are driven by the Web3 community.',
    field: ['NFT','Game-Fi'],
    twitter: 'https://twitter.com/LegendofCards',
    website: 'https://legendofcards.io/',
  },
  
  {
    id: 39,
    name: 'Afflux',
    logo: '/ecosystems/afflux.jpg',
    desc: '🌊Brand Creator 🔖BRAND + IP + COMMUNITY + PRODUCT = SUPER BRAND 🪬 web3 🅽 ',
    field: ['Others'],
    twitter: 'https://twitter.com/Afflux_con',
  },
  
  {
    id: 40,
    name: 'Travel Care',
    logo: '/ecosystems/travelcare.png',
    desc: 'Fly with Crypto!',
    field: ['Others'],
    twitter: 'https://twitter.com/TravelCareToken',
    website: 'https://www.travelcare.io/',
  },
  
  {
    id: 41,
    name: 'Only1',
    logo: '/ecosystems/only1.jpg',
    desc: 'Membership site where creators earn with their fans',
    field: ['Social-Fi'],
    twitter: 'https://twitter.com/JoinOnly1',
    website: 'https://only1.app/',
  },
  
  {
    id: 42,
    name: 'Monsterra',
    logo: '/ecosystems/monsterra.webp',
    desc: '#1 Multi-chain #NFTGame with Free to Play & Earn mechanism on BNB',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/Monsterra_P2E',
    website: 'https://monsterra.io/',
  },
  
  {
    id: 43,
    name: 'DeFi Land',
    logo: '/ecosystems/defiland.webp',
    desc: 'DeFi, Gaming, NFTs and Alpacas in a new and all-in-one game ecosystem🚜',
    field: ['DeFi','Game-Fi'],
    twitter: 'https://twitter.com/DeFi_Land',
    website: 'https://play.defiland.app/',
  },
  
  {
    id: 44,
    name: 'Odsy',
    logo: '/ecosystems/odsy.svg',
    desc: 'Odsy provides a secure, programmable, decentralized access layer to all of web3 through dynamic, decentralized wallets (dWallets).',
    field: ['Wallet','Infrastructure'],
    twitter: 'https://twitter.com/Odsyxyz',
    website: 'https://odsy.xyz/',
  },
  
  {
    id: 45,
    name: 'Perion',
    logo: '/ecosystems/perion.jpg',
    desc: 'Accelerating the shift to Web3 gaming.',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/PerionDAO',
    website: 'https://perion.gg/',
  },
  
  {
    id: 46,
    name: 'MAP Protocol',
    logo: '/ecosystems/mapo.webp',
    desc: 'A Bitcoin layer-2 and peer-to-peer omnichain infrastructure built upon light clients and ZK technology, focusing on cross-chain interoperability.',
    field: ['Infrastructure'],
    twitter: 'https://twitter.com/MapProtocol',
    website: 'https://www.mapprotocol.io/',
  },
  
  {
    id: 47,
    name: 'Anichess',
    logo: '/ecosystems/anichess.jpg',
    desc: 'Community-driven, free-to-play chess game with new strategic layers powered by magical spells.',
    field: ['Game-Fi'],
    twitter: 'https://twitter.com/AnichessGame',
    website: 'https://anichess.com/',
  },
  
  {
    id: 48,
    name: 'Blockless',
    logo: '/ecosystems/blockless.jpg',
    desc: 'Building the first modular application architecture',
    field: ['Infrastructure'],
    twitter: 'https://twitter.com/theblockless',
    website: 'https://blockless.network/',
  },
  
  {
    id: 49,
    name: 'Hooked Protocol',
    logo: '/ecosystems/hooked.webp',
    desc: 'An immersive edutainment network, on-ramp for next billion people onto web3.  ',
    field: ['Others'],
    twitter: 'https://twitter.com/HookedProtocol',
    website: 'https://hooked.io/',
  },
  
  {
    id: 50,
    name: 'Joystream',
    logo: '/ecosystems/joystream.jpg',
    desc: 'A video platform protocol.',
    field: ['Social-Fi','Others'],
    twitter: 'https://twitter.com/JoystreamDAO',
    website: 'https://www.joystream.org/',
  },
  
  {
    id: 51,
    name: 'Ender Protocol',
    logo: '/ecosystems/ender.png',
    desc: 'Metaverse Bond backed by Liquid Staking Power (LSP)',
    field: ['DeFi','Metaverse'],
    twitter: 'https://twitter.com/EnderProtocol',
    website: 'https://www.enderprotocol.io/',
  },
  {
    id: 52,
    name: 'WIS',
    logo: '/ecosystems/wis.jpg',
    desc: 'WIS is a Web3 event platform; Redefine your social experience with WIS, where connection, engagement, and inspiration reach unprecedented levels.',
    field: ['Social-Fi','Campaign'],
    twitter: 'https://twitter.com/WorldinShadow',
    website: 'https://wis.global/',
  },
  {
    id: 53,
    name: 'Aspecta',
    logo: '/ecosystems/aspecta.svg',
    desc: '🚀AI-powered identity network to empower builders and foster ecosystem growth: Every Aspect of Your Builder Adventure',
    field: ['DID'],
    twitter: 'https://twitter.com/aspecta_id',
    website: 'https://aspecta.id/',
  },
  {
    id: 54,
    name: 'Vortex',
    logo: '/ecosystems/vortex.png',
    desc: 'Aggregate liquidity🚀 ZK-SNARKS dex with sub-sites',
    field: ['DEX','DeFi'],
    twitter: 'https://twitter.com/VortexDexOffice',
    website: 'https://www.vortex.ink/',
  },
  {
    id: 55,
    name: 'Wongta',
    logo: '/ecosystems/wongta.svg',
    desc: 'Wongta is a social entertainment platform and digital identity ecosystem built on NFT 3.0 technology.',
    field: ['Social-Fi','NFT'],
    twitter: 'https://twitter.com/wongta_nft',
    website: 'https://www.wongta.com/',
  },
  {
    id: 56,
    name: 'Mallconomy',
    logo: '/ecosystems/mallconomy.webp',
    desc: 'Become an early member of Mallconomy\'s Decentralized Society ("#DeSoc") retail and shopping community to empower creators and shoppers alike in the #Metaverse.',
    field: ['Metaverse'],
    twitter: 'https://twitter.com/mallconomy',
    website: 'https://go.mallconomy.com/',
  },
  {
    id: 57,
    name: 'Klein Labs',
    logo: '/ecosystems/kleinlabs.jpg',
    desc: 'Backing top #Web3 startups with funding, advisory & incubation',
    field: ['Others'],
    twitter: 'https://twitter.com/kleinlabsxyz',
    website: 'https://www.kleinlabs.xyz/',
  },
  {
    id: 58,
    name: 'Vino Chain',
    logo: '/ecosystems/vinochain.jpg',
    desc: 'A real asset trading platform that capitalizes wine and provides liquidity and a token economic model',
    field: ['De-Fi','Others'],
    twitter: 'https://twitter.com/WorldinShadow',
  },
  {
    id: 59,
    name: 'TripleC',
    logo: '/ecosystems/triplec.svg',
    desc: 'Your On-chain #GameFi Achievement System',
    field: ['Social-Fi','Campaign', 'DID'],
    twitter: 'https://twitter.com/TriplecPlatform',
    website: 'https://www.triplec.cc/',
  },
  {
    id: 60,
    name: 'MEME Exchange',
    logo: '/ecosystems/memeexchange.png',
    desc: 'MEME Exchange, Mining Pool, Defi, Launch Pad, Top MEME exchange',
    field: ['CEX','Campaign'],
    twitter: 'https://twitter.com/MEMEcex',
    website: 'https://www.bimeme.com/',
  },
  {
    id: 61,
    name: 'Astar Network',
    logo: '/ecosystems/astar.svg',
    desc: 'A Scalable Network Powering a Global Web3 Vision for All.',
    field: ['Layer 1'],
    twitter: 'https://twitter.com/AstarNetwork',
    website: 'https://unstoppable.astar.network/',
  },
  {
    id: 62,
    name: 'Scroll',
    logo: '/ecosystems/scroll.jpg',
    desc: 'Scroll seamlessly extends Ethereum’s capabilities through zero knowledge tech and EVM compatibility. The L2 network built by Ethereum devs for Ethereum devs.',
    field: ['Layer 2'],
    twitter: 'https://twitter.com/Scroll_ZKP',
    website: 'https://scroll.io/',
  },
]